### ISSUE TITLE
Long search/command strings cause rendering issues on pressing enter

### ISSUE THREAD

**Issue by mbarbar** [krpors/hx#16] opened 2017-11-20 03:54 UTC
Not much to say as this [this](https://asciinema.org/a/PuvnzXKaH61GKeOElxf85SgB3) shows it all.

**Comment by krpors** [comment] 2017-11-20 13:13
Thanks for reporting. Seems to be related to a memory access error (reading past buffer size). Valgrind confirms this:

	$ valgrind ./hx hx
	==3365== Memcheck, a memory error detector
	==3365== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
	==3365== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
	==3365== Command: ./hx hx
	==3365== 
	==3365== 
	==3365== HEAP SUMMARY:
	==3365==     in use at exit: 0 bytes in 0 blocks
	==3365==   total heap usage: 401 allocs, 401 frees, 221,395 bytes allocated
	==3365== 
	==3365== All heap blocks were freed -- no leaks are possible
	==3365== 
	==3365== For counts of detected and suppressed errors, rerun with: -v
	==3365== Use --track-origins=yes to see where uninitialised values come from
	==3365== ERROR SUMMARY: 9 errors from 4 contexts (suppressed: 0 from 0)

I have no Git access from work (proxy cruft...) so I'll attempt to check this later this week.

**Comment by krpors** [comment] 2017-11-22 21:22
This seems to be the fix:

	diff --git a/editor.c b/editor.c
	index 614ad0a..e1e6ec8 100644
	--- a/editor.c
	+++ b/editor.c
	@@ -927,7 +927,7 @@ int editor_read_string(struct editor* e, char* dst, int len) {
	 
		// Safety guard. Our inputbuffer size is limited so stop
		// incrementing our buffer index after this maximum.
	-       if ((size_t) e->inputbuffer_index >= sizeof(e->inputbuffer)) {
	+       if ((size_t) e->inputbuffer_index >= sizeof(e->inputbuffer) - 1) {
		        return c;
		}

The bug was effectively caused by a faulty safeguard. Without the explicit subtraction, there's no room in the buffer to write a null terminator at the end of the string.

**Comment by krpors** [comment] 2017-11-22 21:30
Fixed in 58d0a3860ff!

**Comment by mbarbar** [comment] 2017-11-23 03:16
I gave the fix a shot, sadly it doesn't seem to work for me. The valgrind errors (but one) are gone though.
[Here's](https://asciinema.org/a/gJI1Dz3NT9zLJLB7RHHcINk3M) a demo.

**Edit**
I tried in the TTY and there were no issues. That prompted me to think it might be a size issue (not sure how to minimise the TTY), and yes, whenever the message at the bottom (like "String not found: 'aaaaaaa...'") is two lines, the issue occurs.

I'm heading out for the day so I'll maybe investigate some more later.

**Comment by krpors** [comment] 2017-11-24 09:58
I pushed a fix which fixes the rendering issues. Could you check? Also, I can't seem to reproduce the valgrind error you mentioned, so I need some help figuring that out.

**Comment by mbarbar** [comment] 2017-11-25 03:28
>I pushed a fix which fixes the rendering issues. Could you check?

Seems to work great!

>Also, I can't seem to reproduce the valgrind error you mentioned, so I need some help figuring that out.

Apologies I should've been clearer being that environments are finicky.

```
valgrind -v --track-origins=yes ./hx hx
... bunch of stuff ...
==8112== HEAP SUMMARY:
==8112==     in use at exit: 0 bytes in 0 blocks
==8112==   total heap usage: 23 allocs, 23 frees, 85,169 bytes allocated
==8112== 
==8112== All heap blocks were freed -- no leaks are possible
==8112== 
==8112== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==8112== 
==8112== 1 errors in context 1 of 1:
==8112== Conditional jump or move depends on uninitialised value(s)
==8112==    at 0x10ADE1: editor_process_command (in /home/mohamad/hx/hx)
==8112==    by 0x10BEB3: editor_process_keypress (in /home/mohamad/hx/hx)
==8112==    by 0x10931F: main (in /home/mohamad/hx/hx)
==8112==  Uninitialised value was created by a heap allocation
==8112==    at 0x4C2CE5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8112==    by 0x10C3BA: editor_init (in /home/mohamad/hx/hx)
==8112==    by 0x1092CC: main (in /home/mohamad/hx/hx)
==8112== 
==8112== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

This is from just quitting immediately. Initially I thought it was an alignment thing, so there's some "gap" bytes in the `editor` struct `malloc`'d in `editor_init` being read (maybe a full copy or something), and `calloc` fixes the issue. Then I noticed `editor_init` does not initialise the `dirty` field. Initialising it seems to fix. I can make a PR later on if you haven't gotten to it already.

**Comment by krpors** [comment] 2017-11-25 11:28
Thanks :+1:

**Closed as completed by krpors** 2017-11-25 11:28 UTC
